dontChroot: false
timeout: 999
verbose: false

script:
    # Delete ISO package and init pacman keys
    - command: "pacman -Rdd --noconfirm vincent-os-calamares vincent-os-calamares-settings mkinitcpio-archiso"
    - command: "pacman-key --init"
    - command: "pacman-key --populate archlinux vincent-os"
    # Rebuild initcpio
    - command: "mkinitcpio -P"

i18n:
    name: "[POST-INSTALL] Optimization of packages."
